# Data Engineering 1: Lab 06
---------------

### Task 01: Consistent Hashing
#### Fill the parts marked with Todo for a complete implementation of Consistent Hashing

In [68]:
import names
import pandas as pd

#returns list of size n with random names
def getData(n):
    data = []
    i = 0
    while i < n:
        data.append(names.get_first_name())
        i += 1
    return data

#returns list of hash values for list of data
def getHashs(data):
    hashs = []
    for word in data:
        hashs.append(abs(hash(word)) % (10 ** 8))
    return hashs

#returns list of size m with random server names
def getServers(m):
    data = []
    i = 0
    while i < m:
        data.append('Server_' + names.get_first_name())
        i += 1
    return data

#TodO: create a DataFrame with the list created with the function getdata(100) 
# and a type column filled with the type key

#Todo: add a column to the DataFrame with the hashs created with the getHashs() method

#Todo: create m servers with the getServers function and add them to the DataFrame with the type server

#Todo: add a column to the DataFrame with the angle on the circle

#Todo: add a column to the DataFrame with the corresponding server

#Todo: print the final DataFrame

              name    type  hashvalue       angle          server
8            Tommy     key    7745270   31.828250    Server_Scott
12    Server_Scott  server   15635353   64.251591    Server_Scott
4          Richard     key   17349469   71.295543  Server_Darnell
7            Frank     key   29741850  122.220533  Server_Darnell
9            Staci     key   31404331  129.052298  Server_Darnell
2            Elsie     key   41295011  169.696850  Server_Darnell
1          Kathryn     key   41737086  171.513504  Server_Darnell
0          Jessica     key   66744287  274.277570  Server_Darnell
5           Marion     key   69940934  287.413804  Server_Darnell
3          Marlene     key   79341574  326.044596  Server_Darnell
11  Server_Darnell  server   83162557  341.746463  Server_Darnell
10    Server_Larry  server   86789583  356.651288    Server_Larry
6          Yolanda     key   87604478  360.000000    Server_Scott

### Task 02: Balanced Consistent Hashing
#### Extend the code from Task 01 to ensure object keys are evenly distributed among servers

### Task 03: Weighted Balanced Consistent Hashing
#### Extend the code from Task 01 to ensure object keys are evenly distributed among servers but also with a weighting of the single servers.